# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Copyright 2019 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---
>
 **Describe the bug**
 A clear and concise description of what the bug is.

 **To Reproduce**

 Steps to reproduce the behavior:
 1. Run '...'
 2. See error

 **Expected behavior**
 A clear and concise description of what you expected to happen.

 **Screenshots**
 If applicable, add screenshots to help explain your problem.

 **Desktop (please complete the following information):**
 - OS: [e.g. MacOS/Debian]
 - Version [e.g. 22]

 **Additional context**
 Add any other context about the problem here.
